import {
  blankContent,
  type Settings,
  type RecordItem,
  type Section,
} from "./model";
const profile = (
  title: string,
  words: string[],
  heading: string,
  intro: string,
  back: string[],
) => ({
  title,
  words,
  heading,
  intro,
  back,
  phrases: back,
  contact: "Have something in mind? Let's make it happen.",
  seoDescription: `Hassana Abdullahi — ${title}. Selected work, ideas and a little curiosity.`,
});
const section = (
  id: string,
  template: Section["template"],
  heading: string,
  scope: Section["scope"] = "general",
): Section => ({
  id,
  template,
  label: heading,
  heading,
  intro: "",
  enabled: true,
  scope,
  image: "",
  alt: "",
  items: [],
});
export const demoSettings: Settings = {
  engineering: true,
  data: true,
  name: "Hassana Abdullahi",
  brand: "hassana",
  signature: "Hassana",
  portrait: "/demo/about.jpg",
  portraitAlt: "Hassana Abdullahi",
  aboutImage: "/demo/about.jpg",
  aboutAlt: "Hassana Abdullahi",
  aboutVideo: "/demo/about-hello.mp4",
  aboutPoster: "/demo/about-hello-poster.jpg",
  aboutVideoDescription:
    "Hassana typing on her laptop, then turning to smile and wave hello.",
  collageImage: "/demo/portrait.jpg",
  collageAlt: "Hassana's illustrated avatar from her original portfolio",
  availability: "Open to meaningful collaborations",
  personal:
    "A curious mind, a love for thoughtful details, and always something new to learn. Sample personal copy — edit before publishing.",
  handle: "",
  email: "",
  socials: [],
  profiles: {
    combined: profile(
      "Front End Engineer & Data Analyst",
      ["ENGINEER", "ANALYST", "EXPLORER", "BUILDER"],
      "Thoughtful interfaces. Meaningful insights.",
      "I bring ideas to life on the web and find the stories in data. Two disciplines, one curious mind — making complex things feel simple.",
      [
        "Building thoughtful web experiences",
        "Turning data into clearer decisions",
        "Sharing what I learn",
      ],
    ),
    engineering: profile(
      "Front End Engineer",
      ["ENGINEER", "CREATOR", "EXPLORER", "BUILDER"],
      "I build things people enjoy using.",
      "I turn ideas into thoughtful, accessible web experiences. Clean interfaces, considered details, and a little curiosity.",
      [
        "Building thoughtful web experiences",
        "Making the web more accessible",
        "Sharing what I learn",
      ],
    ),
    data: profile(
      "Data Analyst",
      ["ANALYST", "EXPLORER", "TUTOR", "BUILDER"],
      "Finding the story behind the numbers.",
      "I explore data, ask useful questions, and turn complex information into clear insights and dashboards.",
      [
        "Turning data into clearer decisions",
        "Exploring patterns and possibilities",
        "Sharing what I learn",
      ],
    ),
  },
  sections: [
    section("about", "about", "A little about me"),
    section("services", "services", "What I do"),
    section("tools", "skills", "My everyday toolkit"),
    section(
      "frontend",
      "engineering-projects",
      "Front End Engineering",
      "engineering",
    ),
    section("data-analysis", "data-projects", "Data Analysis", "data"),
    section("experience", "experience", "Along the way"),
    section("community", "community", "Learning. Sharing. Growing."),
    section("certifications", "certifications", "Milestones"),
    section("testimonials", "testimonials", "Kind words"),
    section("articles", "articles", "Notes from my notebook"),
  ],
  labels: {
    contact: "Contact me",
    viewMore: "View more",
    back: "Back to top",
    scroll: "Scroll to explore",
    cv: "Download CV",
    heroNote: "A little curiosity. A lot of care.",
    badgeTagline: "A CURIOUS MIND ✦ A CREATIVE SOUL",
    idLabel: "ID / HASSANA",
    flipHint: "TAP TO FLIP ↻",
    backEyebrow: "THE OTHER SIDE OF ME",
    backHeading: "What I do.",
    aboutEyebrow: "A LITTLE INTRODUCTION",
    personalLabel: "A little more about me",
    greeting: "hi, I'm Hassana",
    collageNote: "always a work in progress ✦",
    contactEyebrow: "GOOD THINGS START WITH A HELLO",
    connectNote: "Let's connect.",
    sendMessage: "Send a message",
  },
  theme: { ink: "#17152C", paper: "#FAF8F4", accent: "#B9A7F7" },
};
const rec = (
  id: string,
  kind: RecordItem["kind"],
  title: string,
  scope: RecordItem["draft"]["scope"],
  summary: string,
  extra: Partial<RecordItem["draft"]> = {},
): RecordItem => {
  const c = { ...blankContent(), title, slug: id, scope, summary, ...extra };
  return {
    id,
    kind,
    draft: c,
    published: c,
    is_seed: true,
    source: "Labelled demonstration content; not verified professional work",
    archived: false,
  };
};
export const demoRecords: RecordItem[] = [
  rec(
    "sample-interface",
    "project",
    "An interface with intention",
    "engineering",
    "Sample project · Replace with your own work",
    {
      cover: "/demo/engineering.svg",
      alt: "Sample interface composition",
      featured: true,
      category: "Web experience",
      tools: ["React", "TypeScript"],
      body: "This is a demonstration of the engineering project template, not a claim of completed client work.",
      blocks: [
        {
          heading: "The idea",
          body: "Explain the problem, your role and the people this project serves.",
          image: "",
          alt: "",
        },
      ],
    },
  ),
  rec(
    "sample-web-app",
    "project",
    "Small details. Better experiences.",
    "engineering",
    "Sample project · Replace with your own work",
    {
      cover: "/demo/application.svg",
      alt: "Sample application layout",
      featured: true,
      category: "Web application",
      body: "Add your own project overview, contributions, challenges and screenshots here.",
    },
  ),
  rec(
    "sample-dashboard",
    "project",
    "A clearer picture",
    "data",
    "Sample dashboard · Illustrative data only",
    {
      cover: "/demo/dashboard.svg",
      alt: "Illustrative analysis dashboard with sample bar chart",
      featured: true,
      category: "Dashboard & analysis",
      tools: ["SQL", "Power BI"],
      body: "A sample case-study layout. The illustrated chart uses fictional data.",
      blocks: [
        {
          heading: "The question",
          body: "Describe your business question and dataset source.",
          image: "",
          alt: "",
        },
        {
          heading: "From data to decisions",
          body: "Explain the cleaning process, methods, findings and recommendations.",
          image: "",
          alt: "",
        },
      ],
    },
  ),
  rec(
    "sample-insights",
    "project",
    "Patterns worth exploring",
    "data",
    "Sample analysis · Illustrative data only",
    {
      cover: "/demo/analysis.svg",
      alt: "Illustrative data analysis workspace",
      featured: true,
      category: "Exploratory analysis",
      body: "Replace this sample with a verified analysis project.",
    },
  ),
  rec(
    "frontend-service",
    "service",
    "Interfaces that feel right.",
    "engineering",
    "Accessible websites and web applications, built with care.",
  ),
  rec(
    "data-service",
    "service",
    "Data that makes sense.",
    "data",
    "Cleaning, exploration and dashboards that make the story clearer.",
  ),
  rec(
    "teaching-service",
    "service",
    "Knowledge worth sharing.",
    "general",
    "Learning in the open, building together, and making room for curiosity.",
  ),
  ...["React", "TypeScript", "Next.js", "Tailwind CSS"].map((x) =>
    rec(
      x.toLowerCase().replace(/[^a-z]/g, ""),
      "skill",
      x,
      "engineering",
      "Sample tool",
    ),
  ),
  ...["SQL", "Python", "Power BI", "Excel"].map((x) =>
    rec(
      x.toLowerCase().replace(/[^a-z]/g, ""),
      "skill",
      x,
      "data",
      "Sample tool",
    ),
  ),
  rec(
    "sample-notebook",
    "article",
    "A place for ideas in progress",
    "general",
    "Sample article · Your writing will live here.",
    {
      category: "Notebook",
      body: "This is a sample article. Use the editor to share your own notes, tutorials, or reflections. Markdown supports headings, lists, code and links.",
      date: "2026-09-28",
    },
  ),
];
